### ISSUE TITLE
please rename 'aux' dir

### ISSUE THREAD

**Issue by truegff** [PioBeat/CDO-Server-as-Docker-Container#1]
Hi,

I can't do git clone on windows.
'aux' seems to be a reserved word according to [microsoft docs](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces).
"Do not use the following reserved names for the name of a file:
CON, PRN, **AUX**, ..."

Can you please rename it?

Thanks

**Comment by PioBeat** [comment]
Hello,
thanks for this information.
I changed the folder name to "etc". Can you try it again and report whether it is working or not?

**Comment by truegff** [comment]
Hi,

The is issue is solved.

Thank you.
